# Generated by Django 3.2.9 on 2021-11-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_title', models.CharField(max_length=40)),
                ('concert_player', models.CharField(max_length=40)),
                ('concert_location', models.CharField(max_length=40)),
                ('concert_detail', models.TextField(default='')),
                ('concert_image', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
    ]
