# Generated by Django 3.2.9 on 2021-11-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concert_datetime',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
